version: '3.1'

services:

  micro-cli-consignment:
    build: ./consignment-cli

  shippy-service-consignment:
    build: ./
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  shippy-service-vessel:
    build: ./shippy-service-vessel
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"